# Vision processing constants
MIN_CONTOUR_AREA = 10
MAX_INTENSITY = 255
NUM_SEGMENTS = 10
KERNEL_SIZE = (5, 5)
ERODE_ITERATIONS = 10
DILATE_ITERATIONS = 15
GREEN_ERODE_ITERATIONS = 2
GREEN_DILATE_ITERATIONS = 2

# Navigation constants
MAX_RECT_WIDTH = 200
MIN_RIGHT_DEVIATION = 50
MIN_LEFT_DEVIATION = 50
MIN_DDERROR = 50